import Phaser from 'phaser';
import type { CharacterId } from '../../packages/shared/src/index';
export interface ArenaCallbacks { onHealth:(health:number)=>void; onEvent:(message:string)=>void; }
let pendingCallbacks:ArenaCallbacks|undefined;
let pendingCharacter:CharacterId='diego';
class ArenaScene extends Phaser.Scene {
 private player!: Phaser.Physics.Arcade.Sprite; private cursors!: Phaser.Types.Input.Keyboard.CursorKeys; private keys!: Record<string,Phaser.Input.Keyboard.Key>; private bullets!: Phaser.Physics.Arcade.Group; private targets!: Phaser.Physics.Arcade.Group; private callbacks!: ArenaCallbacks; private character:CharacterId='diego'; private aim={x:1,y:0}; private lastShot=0;
 constructor(){super({key:'arena'})}
 create(data?:{callbacks:ArenaCallbacks;character:CharacterId}){const config=data??{callbacks:pendingCallbacks!,character:pendingCharacter};this.callbacks=config.callbacks;this.character=config.character;this.physics.world.setBounds(0,0,1600,540);this.cameras.main.setBounds(0,0,1600,540).setZoom(1.5);this.cursors=this.input.keyboard!.createCursorKeys();this.keys=this.input.keyboard!.addKeys('W,A,S,D,SPACE,Q,E,SHIFT') as Record<string,Phaser.Input.Keyboard.Key>;this.makeTexture('actor',34,52,0xffffff);this.makeTexture('bullet',8,8,0xffffff);this.add.rectangle(800,270,1600,540,0x0c1724).setOrigin(.5);for(let x=0;x<1600;x+=64)this.add.rectangle(x+32,470,64,140,0x29463f).setStrokeStyle(2,0x6d9c78);this.add.rectangle(800,526,1600,28,0x12231f);const cover=[{x:440,y:426,w:100,h:88},{x:760,y:390,w:100,h:160},{x:1040,y:430,w:150,h:80},{x:1290,y:410,w:130,h:120}];for(const c of cover)this.add.rectangle(c.x,c.y,c.w,c.h,0x42586b).setStrokeStyle(3,0x87a6a6).setData('hp',100);this.player=this.physics.add.sprite(250,430,'actor').setDisplaySize(34,52).setTint(0x64d9da).setCollideWorldBounds(true);this.player.setBodySize(22,44).setOffset(5,8);this.targets=this.physics.add.group();[1100,1250,1430].forEach((x,i)=>{const t=this.targets.create(x,430,'actor').setDisplaySize(34,52).setTint([0xff6b74,0xffb762,0x9bd879][i]);t.setImmovable(true);t.setData('hp',100)});this.bullets=this.physics.add.group();this.physics.add.collider(this.player,this.targets);this.physics.add.overlap(this.bullets,this.targets,(bullet,target)=>this.hitTarget(bullet as Phaser.Physics.Arcade.Sprite,target as Phaser.Physics.Arcade.Sprite));this.cameras.main.startFollow(this.player,true,.12,.12);this.input.on('pointermove',(p:Phaser.Input.Pointer)=>this.setAim(p.worldX-this.player.x,p.worldY-this.player.y));this.input.on('pointerdown',()=>this.shoot());this.callbacks.onEvent(`M0 sandbox ready // ${this.character.toUpperCase()} loaded`)}
 private makeTexture(key:string,w:number,h:number,color:number){const g=this.add.graphics();g.fillStyle(color);g.fillRect(0,0,w,h);g.generateTexture(key,w,h);g.destroy()}
 private setAim(x:number,y:number){const l=Math.hypot(x,y)||1;this.aim={x:x/l,y:y/l}}
 private shoot(){const now=this.time.now;if(now-this.lastShot<220)return;this.lastShot=now;const b=this.bullets.create(this.player.x+this.aim.x*24,this.player.y-18+this.aim.y*24,'bullet') as Phaser.Physics.Arcade.Sprite;b.setDisplaySize(8,8).setTint(this.character==='diego'?0xd9f36a:0x72ddff);b.setVelocity(this.aim.x*620,this.aim.y*620);b.setData('damage',this.character==='diego'?24:18);this.callbacks.onEvent('Tracer fired // server intent placeholder')}
 private hitTarget(bullet:Phaser.Physics.Arcade.Sprite,target:Phaser.Physics.Arcade.Sprite){bullet.destroy();const hp=Math.max(0,(target.getData('hp') as number)-(bullet.getData('damage') as number));target.setData('hp',hp);target.setAlpha(hp/100+.25);this.callbacks.onEvent(`Impact confirmed // target ${hp} HP`);if(hp===0){target.setTint(0x414c55);target.body?.stop()}}
 update(){const speed=this.keys.SHIFT?.isDown?260:170;let x=0,y=0;if(this.keys.A?.isDown||this.cursors.left.isDown)x-=1;if(this.keys.D?.isDown||this.cursors.right.isDown)x+=1;if(this.keys.W?.isDown||this.cursors.up.isDown)y=-1;if(this.keys.S?.isDown||this.cursors.down.isDown)y=1;this.player.setVelocity(x*speed,y*speed);if(this.input.activePointer.isDown)this.setAim(this.input.activePointer.worldX-this.player.x,this.input.activePointer.worldY-this.player.y);if(this.keys.SPACE?.isDown)this.shoot();if(this.keys.Q?.isDown)this.callbacks.onEvent('Ability intent // cooldown validation belongs on server')}
}
export function createPixelArena(parent:HTMLElement,callbacks:ArenaCallbacks,character:CharacterId){pendingCallbacks=callbacks;pendingCharacter=character;return new Phaser.Game({type:Phaser.CANVAS,width:480,height:270,parent,backgroundColor:'#08111b',pixelArt:true,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},physics:{default:'arcade',arcade:{gravity:{x:0,y:0},debug:false}},scene:{key:'arena',create(this:Phaser.Scene){this.add.rectangle(240,135,480,270,0x0b1b27);for(let x=0;x<480;x+=32)this.add.rectangle(x+16,235,32,70,0x29463f).setStrokeStyle(1,0x6d9c78);this.add.rectangle(240,263,480,14,0x12231f);for(const c of [{x:135,y:195,w:42,h:80},{x:250,y:175,w:42,h:120},{x:370,y:205,w:55,h:60}])this.add.rectangle(c.x,c.y,c.w,c.h,0x42586b).setStrokeStyle(2,0x87a6a6);this.add.circle(74,205,14,0x64d9da).setStrokeStyle(2,0xd9f36a);this.add.circle(405,205,14,0xff6b74).setStrokeStyle(2,0xffb762);this.add.text(18,18,`M0 TRAINING RANGE // ${character.toUpperCase()}`,{fontFamily:'monospace',fontSize:'9px',color:'#d9f36a'});this.add.text(18,35,'BREAK COVER. MAKE THE PLAY.',{fontFamily:'monospace',fontSize:'8px',color:'#edf2e6'});callbacks.onEvent(`M0 sandbox ready // ${character.toUpperCase()} loaded`)}}})}
