import type { CharacterId, InputCommand, TeamId } from './index';

export const TICK_RATE = 30;
export const WORLD = { width: 1600, height: 540, floorY: 470, cell: 4 } as const;
export type Phase = 'lobby'|'warmup'|'live'|'sudden_death'|'results';
export interface TerrainCell { hp:number; material:'dirt'|'stone'|'metal'|'empty' }
export interface SimPlayer { id:string; name:string; team:TeamId; character:CharacterId; x:number; y:number; vx:number; vy:number; health:number; alive:boolean; kills:number; deaths:number; respawnAt:number; input:InputCommand; lastFire:number; }
export interface SimState { tick:number; phase:Phase; timeLeft:number; players:Record<string,SimPlayer>; terrain:TerrainCell[]; events:SimEvent[] }
export type SimEvent = { type:'shot'|'impact'|'destroy'|'death'|'respawn'; tick:number; playerId?:string; targetId?:string; x?:number; y?:number; damage?:number; cells?:number[] };

export function terrainIndex(x:number,y:number){return y*(WORLD.width/WORLD.cell)+x}
export function createTerrain(){const cols=WORLD.width/WORLD.cell, rows=WORLD.height/WORLD.cell;const cells:Array<TerrainCell>=Array.from({length:cols*rows},()=>({hp:0,material:'empty'}));for(let x=0;x<cols;x++){for(let y=Math.floor(WORLD.floorY/WORLD.cell);y<rows;y++){const hp=y>rows-10?100:65;cells[terrainIndex(x,y)]={hp,material:y>rows-5?'stone':'dirt'}}}for(const p of [{x:430,w:24,h:22},{x:740,w:25,h:38},{x:1010,w:34,h:20},{x:1280,w:30,h:28}]){for(let x=p.x;x<p.x+p.w;x++)for(let y=Math.floor(WORLD.floorY/WORLD.cell)-p.h;y<Math.floor(WORLD.floorY/WORLD.cell);y++)cells[terrainIndex(x,y)]={hp:100,material:'stone'}}return cells}
export function createPlayer(id:string,name:string,team:TeamId,character:CharacterId,slot:number):SimPlayer{return{id,name,team,character,x:team==='red'?150+slot*35:1450-slot*35,y:WORLD.floorY-35,vx:0,vy:0,health:100,alive:true,kills:0,deaths:0,respawnAt:0,input:{seq:0,moveX:0,jump:false,crouch:false,aimAngle:0,fire:false,block:false,ability:false,dash:false},lastFire:-999}}
export function createState():SimState{return{tick:0,phase:'lobby',timeLeft:480,players:{},terrain:createTerrain(),events:[]}}
function solidAt(state:SimState,x:number,y:number){const cx=Math.floor(x/WORLD.cell),cy=Math.floor(y/WORLD.cell);if(cx<0||cx>=WORLD.width/WORLD.cell||cy<0||cy>=WORLD.height/WORLD.cell)return true;return state.terrain[terrainIndex(cx,cy)].hp>0}
function destroyTerrain(state:SimState,x:number,y:number,radius:number){const cells:number[]=[];const minX=Math.max(0,Math.floor((x-radius)/WORLD.cell)),maxX=Math.min(WORLD.width/WORLD.cell-1,Math.floor((x+radius)/WORLD.cell));const minY=Math.max(0,Math.floor((y-radius)/WORLD.cell)),maxY=Math.min(WORLD.height/WORLD.cell-1,Math.floor((y+radius)/WORLD.cell));for(let cx=minX;cx<=maxX;cx++)for(let cy=minY;cy<=maxY;cy++){const dx=cx*WORLD.cell+2-x,dy=cy*WORLD.cell+2-y;if(Math.hypot(dx,dy)<=radius){const cell=state.terrain[terrainIndex(cx,cy)];if(cell.hp>0){cell.hp=Math.max(0,cell.hp-60);if(cell.hp===0){cell.material='empty';cells.push(terrainIndex(cx,cy))}}}}return cells}
function fire(state:SimState,p:SimPlayer){const angle=p.input.aimAngle;const speed=18;let x=p.x,y=p.y-20;for(let i=0;i<100;i++){x+=Math.cos(angle)*speed;y+=Math.sin(angle)*speed;if(x<0||x>WORLD.width||y<0||y>WORLD.height)break;const target=Object.values(state.players).find(t=>t.alive&&t.team!==p.team&&Math.hypot(t.x-x,t.y-y)<22);if(target){target.health-=24;state.events.push({type:'impact',tick:state.tick,playerId:p.id,targetId:target.id,x,y,damage:24});if(target.health<=0){target.health=0;target.alive=false;target.deaths++;target.respawnAt=state.tick+TICK_RATE*3;p.kills++;state.events.push({type:'death',tick:state.tick,playerId:p.id,targetId:target.id});}break}const destroyed=destroyTerrain(state,x,y,5);if(destroyed.length){state.events.push({type:'destroy',tick:state.tick,playerId:p.id,x,y,cells:destroyed});break}}state.events.push({type:'shot',tick:state.tick,playerId:p.id,x:p.x,y:p.y})}
export function step(state:SimState){state.tick++;state.events=[];if(state.phase==='warmup'&&state.tick>=TICK_RATE*3)state.phase='live';if(state.phase==='live')state.timeLeft=Math.max(0,480-Math.floor(state.tick/TICK_RATE));for(const p of Object.values(state.players)){if(!p.alive){if(state.tick>=p.respawnAt){p.alive=true;p.health=100;p.x=p.team==='red'?150:1450;p.y=WORLD.floorY-35;state.events.push({type:'respawn',tick:state.tick,playerId:p.id})}continue}const input=p.input;const speed=input.dash?8:4.2;p.vx=input.moveX*speed;p.x=Math.max(20,Math.min(WORLD.width-20,p.x+p.vx));if(input.jump&&p.y>=WORLD.floorY-40&&!solidAt(state,p.x,p.y+25))p.vy=-11;p.vy+=.55;p.y+=p.vy;if(p.y>WORLD.floorY-35){p.y=WORLD.floorY-35;p.vy=0}if(input.fire&&state.tick-p.lastFire>=Math.floor(TICK_RATE*.28)){p.lastFire=state.tick;fire(state,p)}}if(state.phase==='live'&&state.timeLeft===0)state.phase='results';return state}
export function publicSnapshot(state:SimState){return{tick:state.tick,phase:state.phase,timeLeft:state.timeLeft,players:Object.values(state.players).map(({input,lastFire,respawnAt,...p})=>p),terrain:state.terrain,events:state.events}}
