import React,{useEffect,useRef,useState} from 'react';
import type Phaser from 'phaser';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import {CHARACTERS,type CharacterId} from '../packages/shared/src/index';
import {createPixelArena} from './game/PixelArenaGame';
import './style.css';

const supabaseUrl=import.meta.env.VITE_SUPABASE_URL||'https://ktophzsjvpvcvujqymqw.supabase.co';
const supabaseKey=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_1TQAd5MDmrRebBYQQpDwvQ_VZnmpfMr';
const supabase=createClient(supabaseUrl,supabaseKey);

function App(){
 const mount=useRef<HTMLDivElement>(null); const [character,setCharacter]=useState<CharacterId>('diego'); const [event,setEvent]=useState('Waiting for an arena session…'); const [health,setHealth]=useState(100); const [room,setRoom]=useState('SOLO-LOCAL'); const [mobile,setMobile]=useState(false);
 const selected=CHARACTERS.find(c=>c.id===character)!;
 useEffect(()=>{let game:Phaser.Game|undefined;if(mount.current){game=createPixelArena(mount.current,{onHealth:setHealth,onEvent:setEvent},character)}return()=>game?.destroy(true)},[character]);
 useEffect(()=>{supabase.from('matches').select('room_code,phase,arena_id').eq('room_code',room).limit(1).then(({data})=>{if(data?.[0])setEvent(`Room ${data[0].room_code} // ${data[0].phase}`)}).catch(()=>undefined)},[room]);
 return <div className="app"><header><div><span className="eyebrow">PIXEL ARENA / M0–M1 FOUNDATION</span><h1>REAL-TIME <em>2V2</em></h1><p className="sub">Side-view combat. Destructible cover. Two depth lanes. Built for desktop and mobile together.</p></div><div className="connection"><span className="live-dot"/> SUPABASE ONLINE <small>{room}</small></div></header><main className="layout"><aside className="panel left"><div className="panel-title">LOADOUT / FIGHTER</div><div className="character-list">{CHARACTERS.slice(0,6).map(c=><button key={c.id} className={c.id===character?'character selected':'character'} onClick={()=>setCharacter(c.id)}><span className={`portrait ${c.id}`}/><span><b>{c.name}</b><small>{c.role}</small></span><span className="weapon">{c.weapon.replace('_',' ')}</span></button>)}</div><div className="kit"><div className="kit-name">{selected.name} // {selected.role}</div><p>{selected.ability} · {selected.ultimate}</p><div className="stat"><span>HEALTH</span><i><b style={{width:`${health}%`}}/></i><strong>{health}</strong></div><div className="stat"><span>ROOM</span><input value={room} onChange={e=>setRoom(e.target.value.toUpperCase())}/></div></div></aside><section className="arena-panel"><div className="arena-head"><div><span className="eyebrow">TRAINING RANGE / GRASSLAND</span><strong>BREAK COVER. MAKE THE PLAY.</strong></div><div className="score"><span>RED <b>0</b></span><small>08:00</small><span>BLUE <b>0</b></span></div></div><div className="arena" ref={mount}/><div className="event" aria-live="polite"><span>EVENT LOG</span>{event}</div><div className="mobile-toggle"><button onClick={()=>setMobile(!mobile)}>{mobile?'HIDE':'SHOW'} MOBILE CONTROLS</button></div>{mobile&&<div className="mobile-controls"><div className="stick">MOVE</div><div className="mobile-actions"><button>JUMP</button><button>ABILITY</button><button>BLOCK</button><button>ULT</button></div><div className="stick aim">AIM / FIRE</div></div>}</section><aside className="panel right"><div className="panel-title">MATCH FLOW</div><div className="flow active"><b>01 / SANDBOX</b><span>movement + hitscan</span></div><div className="flow"><b>02 / ROOM</b><span>authoritative 2v2</span></div><div className="flow"><b>03 / DESTRUCTION</b><span>4×4 cell grid</span></div><div className="flow"><b>04 / ARCADE</b><span>abilities + objectives</span></div><div className="controls"><div className="panel-title">CONTROLS</div><p><kbd>WASD</kbd> MOVE <kbd>SHIFT</kbd> DASH</p><p><kbd>LMB</kbd> AIM / FIRE <kbd>SPACE</kbd> FIRE</p><p><kbd>Q</kbd> ABILITY <kbd>E</kbd> LANE</p><p className="muted">Mobile uses dual sticks and large action buttons.</p></div></aside></main><footer><span>SERVER-AUTHORITATIVE INTENT MODEL</span><span>GRAFXKID ASSET ANCHOR · SUPABASE PERSISTENCE · COLYSEUS NEXT</span></footer></div>
}
createRoot(document.getElementById('root')!).render(<App/>);
