import './style.css';

type Team='RED'|'BLUE'; type Biome='grassland'|'autumn'|'tropics'|'winter'|'cave'; type Attack='poison'|'arrow'|'fireball'|'seed';
interface Unit{id:string;name:string;team:Team;x:number;y:number;hp:number;maxHp:number;alive:boolean;char:string;attack:Attack;color:string}
interface Shot{x:number;y:number;vx:number;vy:number;owner:Unit;attack:Attack;trail:{x:number;y:number}[];age:number;hits:number}
interface Particle{x:number;y:number;vx:number;vy:number;life:number;kind:'dust'|'rock'|'grass'|'spark';}
const W=1200,H=525,GROUND=468,G=.22;
const base='/assets/';
const assets:Record<string,HTMLImageElement>={};
const sources:Record<string,string>={
  toggle:base+'characters/toggle-idle.png',tracy:base+'characters/tracy-idle.png',percy:base+'characters/percy-idle.png',angie:base+'characters/angie-idle.png',
  toggleShoot:base+'characters/toggle-shoot.png',tracyShoot:base+'characters/tracy-shoot.png',percyShoot:base+'characters/percy-shoot.png',angieShoot:base+'characters/angie-shoot.png',
  poison:base+'projectiles/toggle-bubbles.png',poisonBurst:base+'projectiles/toggle-burst.png',arrow:base+'projectiles/tracy-arrow.png',arrowImpact:base+'projectiles/tracy-impact.png',fireball:base+'projectiles/percy-fireball.png',seed:base+'projectiles/angie-seed.png',seedExplosion:base+'projectiles/angie-explosion.png',
  explosion:base+'fx/explosion.png',dust:base+'fx/dust.png',sparkle:base+'fx/sparkle.png',health:base+'ui/health.png',healthKit:base+'props/health-kit.png',house:base+'props/house.png',
  grassland:base+'biomes/grassland-bg.png',autumn:base+'biomes/autumn-bg.png',tropics:base+'biomes/tropics-bg.png',winter:base+'biomes/winter-bg.png',grassTile:base+'terrain/grassland.png',autumnTile:base+'terrain/autumn.png',tropicsTile:base+'terrain/tropics.png',winterTile:base+'terrain/winter.png',blocks:base+'terrain/blocks.png',rock:base+'terrain/rock.png',lava:base+'terrain/lava.png',water:base+'terrain/water.png'};
for(const [k,src] of Object.entries(sources)){const im=new Image();im.src=src;assets[k]=im}
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<main class="game-shell"><header class="topbar"><div class="brand">IMPACT<b>//</b></div><div class="micro">GRAFXKID COMBAT LAB / ASSET BUILD</div><div class="status"><span class="dot"></span><span class="micro">LOCAL 2V2 TEST</span></div></header><section class="hud-row"><div class="team-card"><div class="team-head red"><span>RED SQUAD</span><span id="red-score">02 / 02</span></div><div class="players" id="red-players"></div></div><div class="turn-card"><div class="turn-label">ACTIVE TURN</div><div class="turn-player">READY // <span id="turn-name">RED-01</span></div><div class="timer" id="timer">00:20</div></div><div class="team-card"><div class="team-head blue"><span>BLUE SQUAD</span><span id="blue-score">02 / 02</span></div><div class="players" id="blue-players"></div></div></section><section class="arena-wrap"><div class="canvas-holder"><canvas id="arena" width="1200" height="525" aria-label="IMPACT battlefield"></canvas><div class="toast" id="toast">IMPACT</div></div><div class="feed" id="feed"><b>RANGE CONTROL:</b> Pick a biome, aim, and fire. Every fighter has a different projectile language.</div><div class="result" id="result" hidden><div class="result-card"><div class="micro">MATCH COMPLETE</div><h2 id="result-title">RED SQUAD WINS</h2><p id="result-copy">The arena is yours.</p><button id="rematch">RUN IT BACK</button></div></div></section><section class="biome-strip"><span class="micro">TERRAIN ROTATION</span><button data-biome="grassland">01 GRASSLAND</button><button data-biome="autumn">02 AUTUMN</button><button data-biome="tropics">03 TROPICS</button><button data-biome="winter">04 WINTER</button><button data-biome="cave">05 CAVE</button><span id="biome-note">Grass / Earth // dirt debris</span></section><section class="bottom-panel"><div class="control-copy"><strong id="selected-title">TOGGLE // POISON BUBBLE PISTOL</strong><small>Move: A / D &nbsp; Aim: mouse &nbsp; Power: distance &nbsp; Fire: SPACE</small></div><div class="weapons"><button class="weapon active" data-attack="primary"><strong>01 PRIMARY</strong><small id="primary-copy">Bubble burst</small></button><button class="weapon" data-attack="special"><strong>02 SPECIAL</strong><small id="special-copy">Wormhole volley</small></button><button class="weapon" data-attack="ultimate"><strong>03 ULTIMATE</strong><small id="ultimate-copy">Team chaos</small></button></div><div class="actions"><button class="restart" id="restart">RESET</button><button class="fire" id="fire">FIRE [SPACE]</button></div></section><div class="help">Q = character ability &nbsp; • &nbsp; 1 / 2 / 3 = attack mode &nbsp; • &nbsp; bots auto-fire for solo testing</div></main>`;
const canvas=document.querySelector<HTMLCanvasElement>('#arena')!,ctx=canvas.getContext('2d')!;ctx.imageSmoothingEnabled=false;
const timerEl=document.querySelector<HTMLDivElement>('#timer')!,turnEl=document.querySelector<HTMLSpanElement>('#turn-name')!,feedEl=document.querySelector<HTMLDivElement>('#feed')!,toastEl=document.querySelector<HTMLDivElement>('#toast')!,resultEl=document.querySelector<HTMLDivElement>('#result')!,resultTitle=document.querySelector<HTMLHeadingElement>('#result-title')!,resultCopy=document.querySelector<HTMLParagraphElement>('#result-copy')!;
const units:Unit[]=[{id:'r1',name:'TOGGLE',team:'RED',x:180,y:404,hp:100,maxHp:100,alive:true,char:'toggle',attack:'poison',color:'#ff6b6b'},{id:'r2',name:'TRACY',team:'RED',x:295,y:407,hp:100,maxHp:100,alive:true,char:'tracy',attack:'arrow',color:'#ffb762'},{id:'b1',name:'PERCY',team:'BLUE',x:930,y:404,hp:100,maxHp:100,alive:true,char:'percy',attack:'fireball',color:'#60e4e1'},{id:'b2',name:'ANGIE',team:'BLUE',x:1040,y:403,hp:100,maxHp:100,alive:true,char:'angie',attack:'seed',color:'#9ddf78'}];
const biomeInfo:Record<Biome,{label:string;bg:string;tile:string;note:string;ground:string;debris:'grass'|'rock'}>={grassland:{label:'GRASSLAND',bg:'grassland',tile:'grassTile',note:'Grass / Earth // dirt debris',ground:'#536f4c',debris:'grass'},autumn:{label:'AUTUMN FOREST',bg:'autumn',tile:'autumnTile',note:'Leaf / Earth // warm fragments',ground:'#765541',debris:'grass'},tropics:{label:'TROPICS',bg:'tropics',tile:'tropicsTile',note:'Water / Earth // wet dust',ground:'#426d65',debris:'grass'},winter:{label:'WINTER WORLD',bg:'winter',tile:'winterTile',note:'Snow / Rock // stone shards',ground:'#667a8b',debris:'rock'},cave:{label:'CAVE TILES',bg:'winter',tile:'rock',note:'Rock / Lava // heavy debris',ground:'#3c3b4f',debris:'rock'}};
let biome:Biome='grassland',terrain:{x:number;y:number;w:number;h:number;kind:'earth'|'rock'|'metal'}[]=[],shots:Shot[]=[],particles:Particle[]=[],active=0,phase:'planning'|'resolving'|'over'='planning',turnEnds=0,aim={x:760,y:260},mode:'primary'|'special'|'ultimate'='primary',last=performance.now(),toastTimeout=0,shake=0;
function reset(){terrain=[{x:420,y:350,w:82,h:118,kind:'rock'},{x:545,y:390,w:110,h:78,kind:'earth'},{x:715,y:332,w:75,h:136,kind:'metal'},{x:830,y:395,w:90,h:73,kind:'earth'},{x:350,y:430,w:570,h:38,kind:'earth'}];shots=[];particles=[];active=0;phase='planning';resultEl.hidden=true;units.forEach((u,i)=>{u.x=[180,295,930,1040][i];u.hp=100;u.alive=true});startTurn();log('RANGE CONTROL',`Biome locked: ${biomeInfo[biome].label}. ${biomeInfo[biome].note}.`)}
function startTurn(){if(checkWinner())return;phase='planning';turnEnds=performance.now()+20000;turnEl.textContent=units[active].name;mode='primary';document.querySelectorAll('.weapon').forEach((b,i)=>b.classList.toggle('active',i===0));updateAttackCopy();if(units[active].team==='BLUE')setTimeout(()=>{if(phase==='planning')botTurn()},700)}
function nextTurn(){let guard=0;do{active=(active+1)%units.length;guard++}while(!units[active].alive&&guard<5);if(!checkWinner())startTurn()}
function checkWinner(){const red=units.some(u=>u.team==='RED'&&u.alive),blue=units.some(u=>u.team==='BLUE'&&u.alive);if(!red||!blue){phase='over';resultTitle.textContent=`${red?'RED':'BLUE'} SQUAD WINS`;resultCopy.textContent=`${red?'Blue':'Red'} squad has been cleared in ${biomeInfo[biome].label}.`;resultEl.hidden=false;return true}return false}
function log(label:string,msg:string){feedEl.innerHTML=`<b>${label}:</b> ${msg}`}
function showToast(msg:string){toastEl.textContent=msg;toastEl.classList.add('show');clearTimeout(toastTimeout);toastTimeout=window.setTimeout(()=>toastEl.classList.remove('show'),800)}
function updateAttackCopy(){const u=units[active];const names:Record<Attack,string>={poison:'Poison bubbles',arrow:'Arrow volley',fireball:'Fireball blast',seed:'Seed cluster'};document.querySelector('#selected-title')!.textContent=`${u.name} // ${names[u.attack].toUpperCase()}`;document.querySelector('#primary-copy')!.textContent=names[u.attack];document.querySelector('#special-copy')!.textContent=u.attack==='arrow'?'Deflect spin':u.attack==='poison'?'Bubble burst':u.attack==='fireball'?'Tail whip':'Seed mine';document.querySelector('#ultimate-copy')!.textContent=u.attack==='seed'?'Garden panic':'Impact cascade'}
function fire(owner=units[active],bot=false){if(phase!=='planning'||!owner.alive)return;phase='resolving';const origin={x:owner.x,y:owner.y-30};let tx=aim.x,ty=aim.y;if(bot){const foes=units.filter(u=>u.team!==owner.team&&u.alive);const target=foes[Math.floor(Math.random()*foes.length)];if(target){tx=target.x+(Math.random()-.5)*70;ty=target.y-20+(Math.random()-.5)*40}}const dx=tx-origin.x,dy=ty-origin.y,n=Math.max(1,Math.hypot(dx,dy)),power=Math.min(16,7+Math.hypot(dx,dy)/55),spread=mode==='special'?[{x:-.12,y:.06},{x:0,y:0},{x:.12,y:-.04}]:mode==='ultimate'?[{x:-.2,y:.1},{x:0,y:0},{x:.2,y:-.1}]:[{x:0,y:0}];for(const s of spread){shots.push({x:origin.x,y:origin.y,vx:(dx/n+s.x)*power,vy:(dy/n+s.y)*power,owner,attack:owner.attack,trail:[],age:0,hits:0})}log(owner.name,`${mode.toUpperCase()} // ${owner.attack.toUpperCase()} launched.`)}
function impact(x:number,y:number,s:Shot){const radius=s.attack==='seed'?70:s.attack==='fireball'?58:s.attack==='poison'?48:40;let hits=0;for(const u of units){if(u.alive&&u.team!==s.owner.team&&Math.hypot(u.x-x,u.y-18-y)<radius+18){const dmg=s.attack==='seed'?18:s.attack==='fireball'?28:s.attack==='poison'?22:32;u.hp=Math.max(0,u.hp-dmg);hits++;if(u.hp===0){u.alive=false;log('ELIMINATION',`${u.name} was removed by ${s.owner.name}.`)}else log('HIT',`${u.name} -${dmg} HP // ${s.attack}`)}}for(const t of terrain){if(Math.hypot(t.x+t.w/2-x,t.y+t.h/2-y)<radius+Math.max(t.w,t.h)/2&&t.kind!=='metal'){t.h*=.5;t.y+=t.h*.4;t.w*=.82}}for(let i=0;i<52;i++)particles.push({x,y,vx:(Math.random()-.5)*(s.attack==='arrow'?4:7),vy:(Math.random()-.75)*7,life:28+Math.random()*36,kind:s.attack==='arrow'?'rock':biomeInfo[biome].debris});shake=10;showToast(hits?`${hits} TARGET${hits>1?'S':''} HIT`:'TERRAIN SHREDDED')}
function botTurn(){if(phase!=='planning')return;const target=units.filter(u=>u.team!==units[active].team&&u.alive)[0];if(target)aim={x:target.x,y:target.y-20};mode=(['primary','special','ultimate'] as const)[Math.floor(Math.random()*3)];fire(units[active],true)}
function update(dt:number){if(phase==='planning'){const left=Math.max(0,turnEnds-performance.now());timerEl.textContent=`00:${String(Math.ceil(left/1000)).padStart(2,'0')}`;timerEl.classList.toggle('warning',left<5000);if(left<=0){if(active===0)fire();else botTurn()}}else if(phase==='resolving'&&shots.length===0){phase='over';setTimeout(()=>{if(!resultEl.hidden)return;nextTurn()},450)}for(const s of [...shots]){s.age+=dt;s.trail.push({x:s.x,y:s.y});if(s.trail.length>15)s.trail.shift();s.x+=s.vx*dt/16;s.y+=s.vy*dt/16;s.vy+=G*dt/16;let hit=s.y>GROUND||s.age>5000;if(s.x<8||s.x>W-8){s.vx*=-.65;s.x=Math.max(8,Math.min(W-8,s.x))}for(const t of terrain)if(s.x>t.x&&s.x<t.x+t.w&&s.y>t.y&&s.y<t.y+t.h)hit=true;for(const u of units)if(u.alive&&u!==s.owner&&Math.hypot(u.x-s.x,u.y-18-s.y)<22)hit=true;if(hit){impact(s.x,s.y,s);shots.splice(shots.indexOf(s),1)}}for(const p of particles){p.x+=p.vx*dt/16;p.y+=p.vy*dt/16;p.vy+=.15*dt/16;p.life-=dt/16}particles=particles.filter(p=>p.life>0);shake=Math.max(0,shake-dt/16)}
function drawImageFrame(im:HTMLImageElement,x:number,y:number,size:number,frame=0){if(!im.complete)return;const fw=32;ctx.imageSmoothingEnabled=false;ctx.drawImage(im,frame*fw,0,fw,Math.min(fw,im.naturalHeight),x-size/2,y-size,size,size)}
function draw(){ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);ctx.clearRect(-20,-20,W+40,H+40);const info=biomeInfo[biome];ctx.fillStyle=info.ground;ctx.fillRect(0,0,W,H);const bg=assets[info.bg];if(bg.complete){ctx.globalAlpha=.9;ctx.drawImage(bg,0,0,bg.naturalWidth,bg.naturalHeight,0,0,W,GROUND+80);ctx.globalAlpha=1}ctx.fillStyle='rgba(7,12,18,.26)';ctx.fillRect(0,0,W,H);ctx.fillStyle=info.ground;ctx.fillRect(0,GROUND,W,H-GROUND);const tile=assets[info.tile];for(let x=0;x<W;x+=16){if(tile.complete)ctx.drawImage(tile,0,0,16,16,x,GROUND-16,16,16)}ctx.strokeStyle='#d7efaa';ctx.globalAlpha=.4;ctx.beginPath();ctx.moveTo(0,GROUND);ctx.lineTo(W,GROUND);ctx.stroke();ctx.globalAlpha=1;for(const t of terrain){ctx.fillStyle=t.kind==='metal'?'#526978':t.kind==='rock'?'#5d5963':info.ground;ctx.strokeStyle=t.kind==='metal'?'#a3cbd0':t.kind==='rock'?'#b2a898':'#a4bd75';ctx.lineWidth=2;ctx.fillRect(t.x,t.y,t.w,t.h);ctx.strokeRect(t.x,t.y,t.w,t.h);for(let xx=t.x+8;xx<t.x+t.w;xx+=16)if(tile.complete)ctx.drawImage(tile,0,0,16,16,xx,t.y,16,16)}if(assets.house.complete&&biome==='grassland')ctx.drawImage(assets.house,0,0,112,96,585,303,112,96);for(const s of shots){ctx.strokeStyle=s.attack==='arrow'?'rgba(241,220,151,.6)':'rgba(211,243,107,.45)';ctx.lineWidth=3;ctx.beginPath();s.trail.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();const key=s.attack==='poison'?'poison':s.attack==='arrow'?'arrow':s.attack==='fireball'?'fireball':'seed',im=assets[key];if(im.complete)ctx.drawImage(im,0,0,16,16,s.x-10,s.y-10,20,20)}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/45);const im=p.kind==='dust'?assets.dust:p.kind==='rock'?assets.explosion:p.kind==='grass'?assets.cloudPoof:assets.sparkle;if(im?.complete)ctx.drawImage(im,0,0,16,16,p.x-8,p.y-8,16,16);else{ctx.fillStyle=p.kind==='rock'?'#b6a48a':'#d1e68b';ctx.fillRect(p.x,p.y,4,4)}}ctx.globalAlpha=1;for(const u of units)drawUnit(u);if(phase==='planning'&&active===0){ctx.strokeStyle='rgba(211,243,107,.6)';ctx.setLineDash([7,8]);ctx.beginPath();ctx.moveTo(units[0].x,units[0].y-30);ctx.lineTo(aim.x,aim.y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#d3f36b';ctx.beginPath();ctx.arc(aim.x,aim.y,5,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#e9f1dc';ctx.font='12px DM Mono';ctx.fillText(`${info.label} // ${info.note}`,24,28);ctx.fillStyle='#d6e5a7';ctx.fillText('GRAFXKID TERRAIN / DESTRUCTIBLE COVER',W-282,28);ctx.restore()}
function drawUnit(u:Unit){if(!u.alive)return;ctx.save();ctx.translate(u.x,u.y);ctx.fillStyle=u.color;ctx.shadowColor=u.color;ctx.shadowBlur=active===units.indexOf(u)?18:5;ctx.beginPath();ctx.arc(0,-20,20,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;drawImageFrame(assets[u.char],0,-3,48);ctx.strokeStyle=u.team==='RED'?'#ff6b6b':'#60e4e1';ctx.lineWidth=3;ctx.strokeRect(-24,-49,48,53);ctx.fillStyle='#0b1017';ctx.fillRect(-24,-61,48,5);ctx.fillStyle=u.team==='RED'?'#ff6b6b':'#60e4e1';ctx.fillRect(-24,-61,48*(u.hp/u.maxHp),5);ctx.fillStyle='#f2f4e3';ctx.font='11px DM Mono';ctx.textAlign='center';ctx.fillText(u.name,0,18);ctx.restore()}
function renderPlayers(){for(const team of ['RED','BLUE'] as Team[]){const el=document.querySelector<HTMLDivElement>(team==='RED'?'#red-players':'#blue-players')!;el.innerHTML=units.filter(u=>u.team===team).map(u=>`<div class="player-chip" style="opacity:${u.alive?1:.35}"><div class="avatar ${u.char}"></div><div><div>${u.name}</div><div class="hp"><i style="width:${u.hp}%"></i></div></div></div>`).join('');document.querySelector<HTMLSpanElement>(team==='RED'?'#red-score':'#blue-score')!.textContent=`${units.filter(u=>u.team===team&&u.alive).length.toString().padStart(2,'0')} / 02`}}
function loop(now:number){const dt=Math.min(34,now-last);last=now;update(dt);renderPlayers();draw();requestAnimationFrame(loop)}
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();aim={x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}});canvas.addEventListener('pointerdown',()=>{if(active===0&&phase==='planning')fire()});document.querySelector('#fire')!.addEventListener('click',()=>fire());document.querySelector('#restart')!.addEventListener('click',reset);document.querySelector('#rematch')!.addEventListener('click',reset);document.querySelectorAll<HTMLButtonElement>('.weapon').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.attack as typeof mode;document.querySelectorAll('.weapon').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));document.querySelectorAll<HTMLButtonElement>('[data-biome]').forEach(b=>b.addEventListener('click',()=>{biome=b.dataset.biome as Biome;document.querySelector('#biome-note')!.textContent=biomeInfo[biome].note;document.querySelectorAll('[data-biome]').forEach(x=>x.classList.toggle('active',x===b));reset()}));window.addEventListener('keydown',e=>{if(e.key===' '){e.preventDefault();fire()}if(['1','2','3'].includes(e.key)){mode=({1:'primary',2:'special',3:'ultimate'} as Record<string,typeof mode>)[e.key];document.querySelector<HTMLButtonElement>(`[data-attack="${mode}"]`)?.click()}if(e.key.toLowerCase()==='q'&&active===0&&phase==='planning'){mode='ultimate';fire();log('ABILITY',`${units[0].name} deployed ${units[0].attack.toUpperCase()} ultimate.`)}});document.querySelector('[data-biome="grassland"]')?.classList.add('active');reset();requestAnimationFrame(loop);
