import './style.css';

type Team = 'RED' | 'BLUE';
type Weapon = 'cannon' | 'cluster' | 'wormhole';
interface Unit { id:string; name:string; team:Team; x:number; y:number; hp:number; maxHp:number; alive:boolean; color:string; sprite:string }
interface Shot { x:number; y:number; vx:number; vy:number; weapon:Weapon; owner:Unit; trail:{x:number;y:number}[]; bounces:number; age:number }
const W=1200,H=525,GROUND=468,GRAVITY=0.22;
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<main class="game-shell"><header class="topbar"><div class="brand">IMPACT<b>//</b></div><div class="micro">LOCAL TEST RANGE / 2V2 ARTILLERY</div><div class="status"><span class="dot"></span><span class="micro">OFFLINE SANDBOX</span></div></header><section class="hud-row"><div class="team-card"><div class="team-head red"><span>RED SQUAD</span><span id="red-score">02 / 02</span></div><div class="players" id="red-players"></div></div><div class="turn-card"><div class="turn-label">ACTIVE TURN</div><div class="turn-player">READY // <span id="turn-name">RED-01</span></div><div class="timer" id="timer">00:20</div></div><div class="team-card"><div class="team-head blue"><span>BLUE SQUAD</span><span id="blue-score">02 / 02</span></div><div class="players" id="blue-players"></div></div></section><section class="arena-wrap"><div class="canvas-holder"><canvas id="arena" width="1200" height="525" aria-label="IMPACT battlefield"></canvas><div class="toast" id="toast">IMPACT</div></div><div class="feed" id="feed"><b>RANGE CONTROL:</b> Fire when ready. Click the arena to aim.</div><div class="result" id="result" hidden><div class="result-card"><div class="micro">MATCH COMPLETE</div><h2 id="result-title">RED SQUAD WINS</h2><p id="result-copy">The arena is yours.</p><button id="rematch">RUN IT BACK</button></div></div></section><section class="bottom-panel"><div class="control-copy"><strong id="selected-title">CANNON // STANDARD ROUND</strong><small>Move: A / D &nbsp; Aim: mouse &nbsp; Power: distance &nbsp; Fire: SPACE</small></div><div class="weapons"><button class="weapon active" data-weapon="cannon"><strong>01 CANNON</strong><small>Reliable / 30 dmg</small></button><button class="weapon" data-weapon="cluster"><strong>02 CLUSTER</strong><small>Three impacts</small></button><button class="weapon" data-weapon="wormhole"><strong>03 WORMHOLE</strong><small>Swap / 18 dmg</small></button></div><div class="actions"><button class="restart" id="restart">RESET</button><button class="fire" id="fire">FIRE [SPACE]</button></div></section><div class="help">Q = special ability &nbsp; • &nbsp; 1 / 2 / 3 = weapon select &nbsp; • &nbsp; bots auto-fire for solo testing</div></main>`;

const canvas=document.querySelector<HTMLCanvasElement>('#arena')!; const ctx=canvas.getContext('2d')!; const timerEl=document.querySelector<HTMLDivElement>('#timer')!; const turnEl=document.querySelector<HTMLSpanElement>('#turn-name')!; const feedEl=document.querySelector<HTMLDivElement>('#feed')!; const toastEl=document.querySelector<HTMLDivElement>('#toast')!; const resultEl=document.querySelector<HTMLDivElement>('#result')!; const resultTitle=document.querySelector<HTMLHeadingElement>('#result-title')!; const resultCopy=document.querySelector<HTMLParagraphElement>('#result-copy')!;
const images:Record<string,HTMLImageElement>={}; for(const [key,src] of Object.entries({percy:'/assets/percy-idle.png',angie:'/assets/angie-idle.png',fireball:'/assets/fireball.png',seed:'/assets/seed-explosion.png'})){const im=new Image();im.src=src;images[key]=im}
const units:Unit[]=[{id:'r1',name:'RED-01',team:'RED',x:180,y:404,hp:100,maxHp:100,alive:true,color:'#ff6b6b',sprite:'percy'},{id:'r2',name:'RED-02',team:'RED',x:290,y:407,hp:100,maxHp:100,alive:true,color:'#ff9d6b',sprite:'angie'},{id:'b1',name:'BLUE-01',team:'BLUE',x:930,y:404,hp:100,maxHp:100,alive:true,color:'#60e4e1',sprite:'angie'},{id:'b2',name:'BLUE-02',team:'BLUE',x:1035,y:403,hp:100,maxHp:100,alive:true,color:'#75a6ff',sprite:'percy'}];
let terrain:{x:number;y:number;w:number;h:number;kind:string}[]=[]; let shots:Shot[]=[]; let particles:{x:number;y:number;vx:number;vy:number;life:number;color:string}[]=[]; let active=0; let selected:Weapon='cannon'; let phase:'planning'|'resolving'|'over'='planning'; let turnEnds=0; let aim={x:760,y:260}; let last=performance.now(); let toastTimeout=0;
function reset(){units[0].x=180;units[1].x=290;units[2].x=930;units[3].x=1035;units.forEach(u=>{u.hp=100;u.alive=true});terrain=[{x:430,y:352,w:80,h:116,kind:'metal'},{x:548,y:390,w:104,h:78,kind:'cover'},{x:720,y:335,w:70,h:133,kind:'metal'},{x:830,y:395,w:90,h:73,kind:'cover'},{x:350,y:430,w:570,h:38,kind:'ground'}];shots=[];particles=[];active=0;phase='planning';resultEl.hidden=true;startTurn();log('RANGE CONTROL','All systems green. RED-01, take the first shot.');}
function startTurn(){if(checkWinner())return;phase='planning';turnEnds=performance.now()+20000;turnEl.textContent=units[active].name;selected='cannon';document.querySelectorAll('.weapon').forEach((b,i)=>b.classList.toggle('active',i===0)); if(units[active].team==='BLUE'||active===1) setTimeout(()=>{if(phase==='planning'&&active>=0)botTurn()},650);}
function nextTurn(){let tries=0;do{active=(active+1)%units.length;tries++}while(!units[active].alive&&tries<5);if(!checkWinner())startTurn();}
function checkWinner(){const red=units.some(u=>u.team==='RED'&&u.alive),blue=units.some(u=>u.team==='BLUE'&&u.alive);if(!red||!blue){phase='over';resultTitle.textContent=`${red?'RED':'BLUE'} SQUAD WINS`;resultCopy.textContent=`${red?'Blue':'Red'} squad has been cleared. Run it back?`;resultEl.hidden=false;return true}return false}
function log(label:string,msg:string){feedEl.innerHTML=`<b>${label}:</b> ${msg}`}
function showToast(msg:string){toastEl.textContent=msg;toastEl.classList.add('show');clearTimeout(toastTimeout);toastTimeout=window.setTimeout(()=>toastEl.classList.remove('show'),700)}
function fire(owner=units[active], bot=false){if(phase!=='planning'||!owner.alive)return;phase='resolving';const origin={x:owner.x,y:owner.y-30};let tx=aim.x,ty=aim.y;if(bot){const foes=units.filter(u=>u.team!==owner.team&&u.alive);const target=foes[Math.floor(Math.random()*foes.length)]||units[0];tx=target.x+(Math.random()-.5)*60;ty=target.y-15+(Math.random()-.5)*40}const dir=owner.team==='RED'?1:-1;const dx=tx-origin.x,dy=ty-origin.y;const distance=Math.max(80,Math.min(470,Math.hypot(dx,dy)));const power=Math.min(15,7+distance/60);const norm=Math.hypot(dx,dy);shots.push({x:origin.x,y:origin.y,vx:dx/norm*power,vy:dy/norm*power,weapon:selected,owner,trail:[],bounces:0,age:0});log(owner.name,`${selected.toUpperCase()} launched${bot?' by tactical bot':''}.`);}
function impact(x:number,y:number,shot:Shot){const blast=shot.weapon==='cluster'?64:shot.weapon==='wormhole'?48:52;let hits=0;for(const u of units){if(!u.alive)continue;const d=Math.hypot(u.x-x,u.y-y);if(u.team!==shot.owner.team&&d<blast+18){const dmg=shot.weapon==='cluster'?18:shot.weapon==='wormhole'?18:30;u.hp=Math.max(0,u.hp-dmg);hits++;if(u.hp===0){u.alive=false;log('ELIMINATION',`${u.name} was deleted from the timeline.`)}else log('DIRECT HIT',`${u.name} -${dmg} HP`);}}for(const t of terrain){if(Math.hypot(t.x+t.w/2-x,t.y+t.h/2-y)<blast+Math.max(t.w,t.h)/2&&t.kind!=='ground'){t.h*=.55;t.y+=t.h*.45;t.w*=.8}}for(let i=0;i<42;i++)particles.push({x,y,vx:(Math.random()-.5)*6,vy:(Math.random()-.7)*6,life:35+Math.random()*25,color:i%3?'#ffb762':'#d3f36b'});showToast(hits?`${hits} TARGET${hits>1?'S':''} HIT`:'TERRAIN SHREDDED');}
function botTurn(){if(phase!=='planning')return;const old=selected;selected=['cannon','cluster','wormhole'][Math.floor(Math.random()*3)] as Weapon;const target=units.filter(u=>u.team!==units[active].team&&u.alive)[0];if(target)aim={x:target.x,y:target.y-20};fire(units[active],true);selected=old}
function update(dt:number){if(phase==='planning'){const remain=Math.max(0,turnEnds-performance.now());timerEl.textContent=`00:${String(Math.ceil(remain/1000)).padStart(2,'0')}`;timerEl.classList.toggle('warning',remain<5000);if(remain<=0){if(active===0)fire();else botTurn()}}else if(phase==='resolving'&&shots.length===0){setTimeout(nextTurn,350);phase='over';setTimeout(()=>{if(phase==='over'&&!resultEl.hidden)return;phase='planning'},350)}for(const s of [...shots]){s.age+=dt;s.trail.push({x:s.x,y:s.y});if(s.trail.length>13)s.trail.shift();s.x+=s.vx*dt/16;s.y+=s.vy*dt/16;s.vy+=GRAVITY*dt/16;let hit=false;if(s.x<8||s.x>W-8){s.vx*=-.65;s.bounces++;s.x=Math.max(8,Math.min(W-8,s.x))}if(s.y<20){s.vy=Math.abs(s.vy)*.7;s.bounces++}for(const t of terrain){if(s.x>t.x&&s.x<t.x+t.w&&s.y>t.y&&s.y<t.y+t.h){hit=true;break}}for(const u of units){if(u.alive&&u!==s.owner&&Math.hypot(u.x-s.x,u.y-18-s.y)<23){hit=true;break}}if(s.y>GROUND||hit||s.age>5000||(s.weapon==='wormhole'&&s.bounces>1)){impact(s.x,s.y,s);shots.splice(shots.indexOf(s),1)}}for(const p of particles){p.x+=p.vx*dt/16;p.y+=p.vy*dt/16;p.vy+=.13*dt/16;p.life-=dt/16}particles=particles.filter(p=>p.life>0);}
function draw(){ctx.clearRect(0,0,W,H);const grd=ctx.createLinearGradient(0,0,0,H);grd.addColorStop(0,'#19293b');grd.addColorStop(1,'#0c141f');ctx.fillStyle=grd;ctx.fillRect(0,0,W,H);ctx.fillStyle='#7e9b9f';for(let i=0;i<34;i++){ctx.globalAlpha=.15+(i%4)*.04;ctx.fillRect((i*137)%W,90+(i*47)%220,2+(i%3),2)}ctx.globalAlpha=1;ctx.fillStyle='#111b25';ctx.fillRect(0,GROUND,W,H-GROUND);ctx.strokeStyle='#425a60';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,GROUND);ctx.lineTo(W,GROUND);ctx.stroke();for(const t of terrain){ctx.fillStyle=t.kind==='metal'?'#3a5260':'#405650';ctx.strokeStyle=t.kind==='metal'?'#73a2a4':'#728e66';ctx.lineWidth=2;ctx.fillRect(t.x,t.y,t.w,t.h);ctx.strokeRect(t.x,t.y,t.w,t.h);ctx.fillStyle='rgba(211,243,107,.14)';for(let x=t.x+9;x<t.x+t.w;x+=18)ctx.fillRect(x,t.y+7,3,3)}for(const s of shots){ctx.strokeStyle='rgba(211,243,107,.42)';ctx.lineWidth=3;ctx.beginPath();s.trail.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();const projectile=images.fireball; if(projectile.complete){ctx.imageSmoothingEnabled=false;ctx.drawImage(projectile,0,0,16,16,s.x-10,s.y-10,20,20)}else{ctx.fillStyle=s.weapon==='cluster'?'#ffb762':'#d3f36b';ctx.beginPath();ctx.arc(s.x,s.y,7,0,Math.PI*2);ctx.fill()}}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/45);if(p.color==='#ffb762'&&images.seed.complete){ctx.imageSmoothingEnabled=false;ctx.drawImage(images.seed,0,0,8,8,p.x-4,p.y-4,12,12)}else{ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,4,4)}}ctx.globalAlpha=1;for(const u of units){drawUnit(u)}if(phase==='planning'&&active===0){ctx.strokeStyle='rgba(211,243,107,.42)';ctx.setLineDash([7,8]);ctx.beginPath();ctx.moveTo(units[0].x,units[0].y-30);ctx.lineTo(aim.x,aim.y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#d3f36b';ctx.beginPath();ctx.arc(aim.x,aim.y,5,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#a3b9c2';ctx.font='12px DM Mono';ctx.fillText('AIM / POWER',26,493);ctx.fillText('DESTRUCTIBLE COVER',W-170,493);}
function drawUnit(u:Unit){if(!u.alive)return;ctx.save();ctx.translate(u.x,u.y);ctx.fillStyle=u.color;ctx.shadowColor=u.color;ctx.shadowBlur=active===units.indexOf(u)?18:5;ctx.beginPath();ctx.arc(0,-20,20,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;const im=images[u.sprite];if(im.complete){ctx.imageSmoothingEnabled=false;ctx.drawImage(im,0,0,32,32,-22,-43,44,44)}ctx.strokeStyle=u.team==='RED'?'#ff6b6b':'#60e4e1';ctx.lineWidth=3;ctx.strokeRect(-23,-47,46,51);ctx.fillStyle='#0b1017';ctx.fillRect(-24,-59,48,5);ctx.fillStyle=u.team==='RED'?'#ff6b6b':'#60e4e1';ctx.fillRect(-24,-59,48*(u.hp/u.maxHp),5);ctx.fillStyle='#e9eff4';ctx.font='11px DM Mono';ctx.textAlign='center';ctx.fillText(u.name,0,17);ctx.restore()}
function renderPlayers(){for(const team of ['RED','BLUE'] as Team[]){const el=document.querySelector<HTMLDivElement>(team==='RED'?'#red-players':'#blue-players')!;el.innerHTML=units.filter(u=>u.team===team).map(u=>`<div class="player-chip" style="opacity:${u.alive?1:.35}"><div class="avatar ${u.sprite}"></div><div><div>${u.name}</div><div class="hp"><i style="width:${u.hp}%"></i></div></div></div>`).join('');document.querySelector<HTMLSpanElement>(team==='RED'?'#red-score':'#blue-score')!.textContent=`${units.filter(u=>u.team===team&&u.alive).length.toString().padStart(2,'0')} / 02`}}
function loop(now:number){const dt=Math.min(34,now-last);last=now;update(dt);renderPlayers();draw();requestAnimationFrame(loop)}
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();aim={x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}});canvas.addEventListener('pointerdown',e=>{if(active===0&&phase==='planning'){const r=canvas.getBoundingClientRect();aim={x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H};fire()}});document.querySelector('#fire')!.addEventListener('click',()=>fire());document.querySelector('#restart')!.addEventListener('click',reset);document.querySelector('#rematch')!.addEventListener('click',reset);document.querySelectorAll<HTMLButtonElement>('.weapon').forEach(b=>b.addEventListener('click',()=>{selected=b.dataset.weapon as Weapon;document.querySelectorAll('.weapon').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#selected-title')!.textContent=selected==='cannon'?'CANNON // STANDARD ROUND':selected==='cluster'?'CLUSTER // TRIPLE IMPACT':'WORMHOLE // POSITION SHIFT'}));window.addEventListener('keydown',e=>{if(e.key===' '){e.preventDefault();fire()}if(['1','2','3'].includes(e.key)){selected=({1:'cannon',2:'cluster',3:'wormhole'} as Record<string,Weapon>)[e.key];document.querySelector<HTMLButtonElement>(`[data-weapon="${selected}"]`)?.click()}if(e.key.toLowerCase()==='q'&&active===0&&phase==='planning'){selected='wormhole';fire();log('SPECIAL','WORMHOLE SWAP deployed.')}});reset();requestAnimationFrame(loop);
