create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null default 'Rookie', selected_character text not null default 'diego', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.matches (id uuid primary key default gen_random_uuid(), room_code text not null unique, mode text not null default 'team_deathmatch' check (mode in ('team_deathmatch','control_point','payload')), phase text not null default 'lobby' check (phase in ('lobby','warmup','live','sudden_death','results')), arena_id text not null default 'grassland', max_players integer not null default 4 check (max_players = 4), created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), started_at timestamptz, ended_at timestamptz);
create table if not exists public.match_players (match_id uuid not null references public.matches(id) on delete cascade, user_id uuid references auth.users(id) on delete set null, session_id text not null, display_name text not null, team text not null check (team in ('red','blue')), character_id text not null default 'diego', kills integer not null default 0, deaths integer not null default 0, connected boolean not null default true, joined_at timestamptz not null default now(), last_seen_at timestamptz not null default now(), primary key (match_id, session_id));
create table if not exists public.match_events (id bigint generated always as identity primary key, match_id uuid not null references public.matches(id) on delete cascade, tick integer not null, event_type text not null, payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index if not exists matches_room_code_idx on public.matches(room_code);
create index if not exists match_players_match_id_idx on public.match_players(match_id);
create index if not exists match_events_match_tick_idx on public.match_events(match_id, tick);
alter table public.profiles enable row level security;
alter table public.matches enable row level security;
alter table public.match_players enable row level security;
alter table public.match_events enable row level security;
drop policy if exists profiles_self on public.profiles;
create policy profiles_self on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
drop policy if exists matches_public_read on public.matches;
create policy matches_public_read on public.matches for select using (true);
drop policy if exists match_players_public_read on public.match_players;
create policy match_players_public_read on public.match_players for select using (true);
drop policy if exists match_events_public_read on public.match_events;
create policy match_events_public_read on public.match_events for select using (true);
